replicaCount: 2

image:
  repository: <your-docker-repository>/laravel-octane
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: myapp.example.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
  - secretName: myapp-tls
    hosts:
      - myapp.example.com


resources: {}

initContainer:
  image: <your-docker-repository>/laravel-octane
  tag: ""
  pullPolicy: IfNotPresent
  command: ["php", "artisan", "migrate"]

env:
  - name: APP_NAME
    value: Laravel
  - name: APP_ENV
    value: production
  - name: APP_DEBUG
    value: false
  - name: LOG_CHANNEL
    value: stack
  - name: DB_CONNECTION
    value: mysql
  - name: DB_HOST
    value: 127.0.0.1
  - name: DB_PORT
    value: "3306"
  - name: DB_DATABASE
    value: laravel
  - name: DB_USERNAME
    value: root
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: DB_PASSWORD
