apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-octane-chart.fullname" . }}
  labels:
    {{- include "laravel-octane-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "laravel-octane-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laravel-octane-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: migrate
        image: "{{ .Values.initContainer.image }}:{{ .Values.initContainer.tag }}"
        imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
        command: {{ toYaml .Values.initContainer.command | nindent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        env:
        {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | default "" }}
            {{- if .valueFrom }}
            valueFrom:
              secretKeyRef:
                name: {{ .valueFrom.secretKeyRef.name }}
                key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
